### ISSUE TITLE
MP3 requirements & stuck on "Encoding..."

### ISSUE THREAD

**Issue by RyveEthan** [KingJackSkellington/nfs-rivals-custom-music#1]
Hey, first thanks for the guide. It's working well so far.
I'm having some issues when I try to convert some songs to an ealayer3 file. The program is sometimes stuck on "Encoding...". The ".ealayer3" file still appears but it doesn't give me the SegmentLenght and the ChunkSize. I followed the instructions to have a "clean" MP3 with Audacity but it doesn't seem to work. Some of my MP3 files are working, some other don't and I'd like to know why if by any chance you can help.

Here's an example of song that doesn't work with dandel-el3. Thanks
[All The Same (Game Version).zip](https://github.com/user-attachments/files/17873734/All.The.Same.Game.Version.zip)

**Comment by RyveEthan** [comment]
Fixed, it comes from a weird version of dandev-el3.exe itself.

**Comment by Mysticc28** [comment]
> Fixed, it comes from a weird version of dandev-el3.exe itself.

@RyveEthan what was the fix? i still get this error no matter which version I use
